---
# k3s server config file.

write-kubeconfig-mode: "0644"
log: "/persist/newlog/kube/k3s.log"
# Use longhorn storage
etcd-arg:
  - "heartbeat-interval=8000"
  - "election-timeout=40000"
  - "quota-backend-bytes=8589934592"
etcd-expose-metrics: true
container-runtime-endpoint: "/run/containerd-user/containerd.sock"
disable-network-policy: true
disable-cloud-controller: true
